services:

  config-server:
    build: ./config-server
    image: config-server
    ports:
      - "8888:8888"
    env_file:
      - .env

  eureka-server:
    build: ./eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    env_file:
      - .env

  api-gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - "9091:8080"
    depends_on:
      - eureka-server
    env_file:
      - .env

  order-service:
    build: ./order-service
    image: order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    env_file:
      - .env

  payment-service:
    build: ./payment-service
    image: payment-service
    ports:
      - "8083:8082"
    depends_on:
      - eureka-server
    env_file:
      - .env

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"