services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - "9091:8080"
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: microservices-logs
        awslogs-stream: api-gateway

  order-service:
    build: ./order-service
    image: order-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: microservices-logs
        awslogs-stream: order-service

  payment-service:
    build: ./payment-service
    image: payment-service
    ports:
      - "8083:8082"
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: microservices-logs
        awslogs-stream: payment-service