services:

  # =========================
  # CONFIG SERVER
  # =========================
  config-server:
    build: ./config-server
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"

  # =========================
  # EUREKA SERVER
  # =========================
  eureka-server:
    build: ./eureka-server
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  # =========================
  # API GATEWAY
  # =========================
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "9091:8080"
    depends_on:
      - eureka-server

  # =========================
  # AUTH SERVICE (JWT ISSUER)
  # =========================
  auth-service:
    build: ./auth-service
    image: auth-service
    container_name: auth-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server

    # üîê JWT KEYS (PERSISTENT)
    volumes:
      - auth-jwt-keys:/app/keys

  # =========================
  # ORDER SERVICE
  # =========================
  order-service:
    build: ./order-service
    image: order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - order-db

  # =========================
  # PAYMENT SERVICE
  # =========================
  payment-service:
    build: ./payment-service
    image: payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - payment-db

  # =========================
  # ORDER DB (POSTGRES)
  # =========================
  order-db:
    image: postgres:15
    container_name: order-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - order-db-data:/var/lib/postgresql/data

  # =========================
  # PAYMENT DB (POSTGRES)
  # =========================
  payment-db:
    image: postgres:15
    container_name: payment-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  # =========================
  # ZIPKIN
  # =========================
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

# =========================
# VOLUMES (PERSISTENT)
# =========================
volumes:
  auth-jwt-keys:
  order-db-data:
  payment-db-data:
