server:
  port: 8082

spring:
  application:
    name: payment-service   # âœ… REQUIRED (Eureka + Zipkin)

  datasource:
 #   url: jdbc:postgresql://localhost:5432/paymentdb
    url: jdbc:postgresql://host.docker.internal:5432/paymentdb
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
 #     host: localhost
      host: host.docker.internal
      port: 6379

# ================================
# EUREKA CONFIG
# ================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ================================
# ACTUATOR + MICROMETER + ZIPKIN
# ================================
management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0   # DEV only (100% tracing)

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# ================================
# RESILIENCE4J CONFIGURATION
# ================================
resilience4j:
  circuitbreaker:
    instances:
      paymentCB:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      paymentRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.RestClientException

  timelimiter:
    instances:
      paymentTL:
        timeout-duration: 2s

  bulkhead:
    instances:
      paymentBH:
        max-concurrent-calls: 10
        max-wait-duration: 0